// --- 9. SINIF KAVRAMLAR SÖZLÜĞÜ (153 KAVRAM) ---
window.KAVRAMLAR = [
    { terim: "Ağırşak", anlam: "Yün veya iplik eğrilen iği ağırlaştırmak için alt ucuna geçirilen yarım küre biçiminde, ortası delik ağaç veya kemik parça." },
    { terim: "Aidiyet", anlam: "Bir şeye ait olma durumu, aitlik." },
    { terim: "Aman Dilemek", anlam: "Önce direnirken zor karşısında boyun eğip canının bağışlanmasını dilemek." },
    { terim: "Amfora", anlam: "İki kulplu, dibi sivri, dar boyunlu, karnı geniş testi." },
    { terim: "Amil", anlam: "İslam halifeleri, hükümdarları ve emîrleri tarafından vergi toplamakla, idare işleriyle, valilikle görevlendirilen kimselere verilen bir unvan." },
    { terim: "Analiz Etmek", anlam: "Anlamı ve niteliği anlaşılamayan bir konuyu açıkladıktan sonra sonuca bağlamak, tahlil etmek." },
    { terim: "Analoji", anlam: "Bazı ortak yönleri bulunan iki şey arasındaki benzeşme, benzeşim." },
    { terim: "Anane", anlam: "Bir toplumda eskiden kalmış olmaları dolayısıyla saygın tutulup kuşaktan kuşağa iletilen, yaptırım gücü olan kültürel kalıntılar, alışkanlıklar, bilgi, töre ve davranışlar; gelenek, örf." },
    { terim: "Antik", anlam: "İlk Çağ’daki uygarlıklarla, özellikle eski Yunan ve Roma uygarlıkları ile ilgili olan." },
    { terim: "Antropoloji", anlam: "İnsanı hem biyolojik ve fiziksel özellikleriyle hem de toplumsal ve kültürel yönleriyle inceleyen bilim." },
    { terim: "Aristokrasi", anlam: "Soylular sınıfı." },
    { terim: "Arkaik", anlam: "Güzel sanatlarda klasik çağ öncesinden kalan; eskicil." },
    { terim: "Arma", anlam: "Bir devletin, bir hanedanın, bir sanayi kuruluşunun veya bir şehrin simgesi olarak kabul edilmiş resim, harf veya şekil; ongun." },
    { terim: "Arrade", anlam: "Muhasaralarda (kuşatmalarda) surları yıkmak için kullanılan savaş aracı, mancınık." },
    { terim: "Arşidük", anlam: "Avusturya’da imparator ailesi prenslerine verilen unvan." },
    { terim: "Aşık Kemiği", anlam: "Çift tırnaklı hayvanların ön dizlerinde bulunan bir eklem kemiği; aşık, kâp." },
    { terim: "Atıf Yapmak", anlam: "Bir başkasının daha önce yayımlanmış bir çalışmasına gönderme yapmak." },
    { terim: "Avam", anlam: "Sıradan insanlar, havas karşıtı." },
    { terim: "Balbal", anlam: "Eski Türklerde kişinin anılması için mezarının veya bazı kurganların etrafına dikilen taş." },
    { terim: "Balta", anlam: "Ağacı kesme, yarma, yontma vb. işlerde kullanılan ağaç saplı, demir araç." },
    { terim: "Başbuğ", anlam: "Eski Türklerde devletin veya ordunun başında olan kimse; Osmanlı Devleti’nde savaş zamanı milis güçlerinin komutanı." },
    { terim: "Bellek", anlam: "Yaşananları, öğrenilen konuları, bunların geçmişle ilişkisini bilinçli olarak zihinde saklama gücü; hafıza." },
    { terim: "Beşerî", anlam: "İnsanoğlu ile ilgili." },
    { terim: "Beytülmal", anlam: "Devletin hazinesi." },
    { terim: "Biat", anlam: "Bir kimsenin egemenliğini tanıma; bir hükümdarın hükmü altına girme." },
    { terim: "Bilim", anlam: "Evrenin veya olayların bir bölümünü konu olarak seçen, deneye dayanan yöntemler ve gerçeklikten yararlanarak sonuç çıkarmaya çalışan düzenli bilgi, ilim." },
    { terim: "Binaenaleyh", anlam: "Bundan dolayı, bunun için, bu açıdan." },
    { terim: "Birinci Elden Kaynaklar", anlam: "Olayların yaşandığı dönemde ya da bu dönemden hemen sonra oluşan veya oluşturulan özgün kaynaklar." },
    { terim: "Broş", anlam: "Yaka iğnesi." },
    { terim: "Büst", anlam: "Heykelcilikte başı, göğsü, bazen de omuzları içine alan sanat ürünü." },
    { terim: "Ceride", anlam: "Kayıt defteri." },
    { terim: "Coğrafya", anlam: "Yeryüzünü fiziki, ekonomik, beşerî ve siyasi yönlerden inceleyen bilim." },
    { terim: "Cumhuriyet", anlam: "Milletin, egemenliği kendi elinde tuttuğu ve bunu belirli süreler için seçtiği milletvekilleri aracılığıyla kullandığı yönetim biçimi." },
    { terim: "Cülus", anlam: "Hükümdarlık tahtına çıkma, tahta oturma." },
    { terim: "Çağ", anlam: "Kendine özgü bir özellik taşıyan zaman parçası; asır, dönem, devir." },
    { terim: "Çanak", anlam: "Toprak, metal vb. bir maddeden yapılmış yayvan, çukurca kap." },
    { terim: "Çapa", anlam: "Tarlalarda toprağı işlemek için kullanılan ağaç veya demir saplı kazı aracı." },
    { terim: "Çiftçi", anlam: "Geçimini toprağı ekerek sağlayan kimse." },
    { terim: "Çömlek", anlam: "Toprak tencere." },
    { terim: "Değişim ve Süreklilik", anlam: "Tarihin statik (durağan) olmadığını, toplumların ve yapıların zamanla farklılaştığını ancak bazı özelliklerin devam ettiğini ifade eden kavramlar." },
    { terim: "Devrim", anlam: "Belli bir alanda hızlı, köklü ve nitelikli değişiklik." },
    { terim: "Dikili Taş", anlam: "Önemli bir olayın durumu veya bir zaferin anısı için dikilmiş tek parça yüksek taş, obelisk." },
    { terim: "Dijital Doğuştan Kaynak (Born Digital)", anlam: "Genel ağ siteleri, e-kitaplar, elektronik kayıtlar gibi doğrudan dijital ortamda üretilen kaynaklar." },
    { terim: "Dijitalleşme", anlam: "Verilerin bilgisayar ortamında okunabilir hale getirilmesi ve işlenmesi süreci." },
    { terim: "Diplomatik", anlam: "Resmî belgeleri şekil ve içerik bakımından inceleyen bilim." },
    { terim: "Disiplin", anlam: "Bir topluluğun yasalarına ve kurallarına uyması durumu; öğretim konusu olan bilgi bütünü veya bilim dalı." },
    { terim: "Doğa Bilimleri", anlam: "Konusu tabiat olayları ve kanunları olan fizik, kimya, biyoloji vb. bilimler." },
    { terim: "Ecdat", anlam: "Geçmişteki büyükler, atalar." },
    { terim: "Edimsel", anlam: "Edim niteliğinde olan, gerçek olarak var olan; fiilî." },
    { terim: "Egemenlik", anlam: "Milletin ve devletin yetkilerinin hepsi; hâkimiyet." },
    { terim: "E-Kitap", anlam: "Bilgisayar, tablet, akıllı telefon gibi cihazlarda okunabilen etkileşimli kitap türü." },
    { terim: "Empati", anlam: "Aynı duyguları paylaşma, duygudaşlık." },
    { terim: "Epigrafi", anlam: "Kitabeleri ve üzerindeki yazıları şekil ve içerik bakımından inceleyen bilim." },
    { terim: "Etik", anlam: "Çeşitli meslek kolları arasında tarafların uyması gereken davranışlar bütünü." },
    { terim: "Etnografya", anlam: "Toplumların yaşayışlarını, hayat tarzlarını, örf ve âdetlerini inceleyen bilim." },
    { terim: "Evcilleştirmek", anlam: "Evcil bir duruma getirmek, ehlîleştirmek." },
    { terim: "Fey Geliri", anlam: "Savaş yapılmadan elde edilen ganimet." },
    { terim: "Filoloji", anlam: "Günümüzde ve geçmişte konuşulan dilleri ve bu dillerin gelişimlerini inceleyen bilim." },
    { terim: "Firari", anlam: "Kaçak, kaçkın." },
    { terim: "Firavun", anlam: "Eski Mısır hükümdarlarına verilen unvan." },
    { terim: "Fresk", anlam: "Yaş duvar sıvası üzerine kireç suyunda eritilmiş madenî boyalarla resim yapma yöntemi ve bu yöntemle yapılan duvar resmi." },
    { terim: "Geçmiş", anlam: "Yaşanmış ve değiştirilemez olayları ifade eden kavram." },
    { terim: "Genel Ağ (Web)", anlam: "Birbirine bağlantılı milyarlarca sayfadan oluşan bir hiper metin sistemi." },
    { terim: "Han", anlam: "Yolcuların konaklamalarına yarayan yapı." },
    { terim: "Hanedan", anlam: "Hükümdar soyu; belli ve köklü bir soydan gelen." },
    { terim: "Havza", anlam: "Sınırları idari, ekonomik birliğe veya coğrafi özelliklere göre belirlenen bölge." },
    { terim: "Hazine", anlam: "Büyük servet; devletin nakit işlemlerini düzenleyen makam." },
    { terim: "Heraldik", anlam: "Resmî belgelerdeki mühür, arma ve özel işaretleri inceleyen bilim." },
    { terim: "Heterojen", anlam: "Ayrı türden, ayrışık." },
    { terim: "Hiper Metin", anlam: "Birbiriyle bağlantılı yazı, görsel, video gibi verileri içeren bir metin organizasyonu." },
    { terim: "Hipodrom", anlam: "At ve araba yarışlarının yapıldığı yer." },
    { terim: "Hiyeroglif", anlam: "Antik Çağ’da Mısırlıların kullandığı resim yazısı." },
    { terim: "İkinci Elden Kaynaklar", anlam: "Olayların yaşanmasından sonra, birinci elden kaynaklara dayandırılarak ortaya konan eserler." },
    { terim: "İkta", anlam: "Devlete ait toprakların gelirlerinin asker veya sivil erkâna hizmet karşılığı verilmesi." },
    { terim: "İlkel", anlam: "Gelişmesinin başında bulunan, basit; zaman bakımından en eski olan." },
    { terim: "İllüstrasyon", anlam: "Kitap içindeki bir yazıyı açıklayan veya süsleyen resim." },
    { terim: "İmparatorluk", anlam: "Kendi topraklarında oturan çeşitli milletleri egemenliği altında toplayan devlet biçimi." },
    { terim: "İnşa Etmek", anlam: "Kurmak, yapmak (Tarihçiler geçmişi belgelerle yeniden inşa ederler)." },
    { terim: "Kabartma (Rölyef)", anlam: "Kil, taş vb. gereçleri girintili çıkıntılı yüzeyler durumunda biçimlendirerek yapılan eser." },
    { terim: "Kağan", anlam: "Hanların bağlı olduğu devlet başkanı." },
    { terim: "Kaide", anlam: "Kural; bir şeyin üzerine oturtulduğu tabanlık." },
    { terim: "Kanıt", anlam: "Tarihsel olay ve olguları destekleyen belgelerden ve kalıntılardan elde edilen veri." },
    { terim: "Kartograf", anlam: "Harita yapan kimse, haritacı." },
    { terim: "Kavim", anlam: "Aralarında töre, dil ve kültür ortaklığı bulunan insan topluluğu; budun." },
    { terim: "Kerpiç", anlam: "Saman ve balçık karışımı, güneşte kurutulmuş ilkel tuğla." },
    { terim: "Kervan", anlam: "Uzak yerlere yolcu ve ticaret eşyası taşıyan yük hayvanı katarı." },
    { terim: "Kimya", anlam: "Maddenin yapısını ve özelliklerini inceleyen, Karbon-14 yöntemiyle buluntuların yaşını belirlemeye yarayan bilim." },
    { terim: "Kıstas", anlam: "Ölçüt, kriter." },
    { terim: "Kompleks", anlam: "Karmaşık, içinde aynı cinsten birçok öge bulunan." },
    { terim: "Kompozit", anlam: "Karma; değişik tarzları bir arada taşıyan." },
    { terim: "Konargöçer", anlam: "Göçebe bir hayat süren, bir yere sürekli yerleşmeyen." },
    { terim: "Konik", anlam: "Koni biçiminde olan." },
    { terim: "Koşut", anlam: "Paralel, aynı zaman içinde gelişen." },
    { terim: "Köken", anlam: "Bir şeyin çıktığı, dayandığı temel; menşe." },
    { terim: "Kronik", anlam: "Günü gününe yazılmış olayları içine alan eser, vakayiname." },
    { terim: "Kronoloji", anlam: "Geçmişten günümüze meydana gelen olayları tarihlendirerek sıralayan zaman bilimi." },
    { terim: "Kurak", anlam: "Yağışı olmayan." },
    { terim: "Kurgan", anlam: "İlk Çağ’da mezar üzerine toprak yığılarak yapılan küçük tepe; tepe biçiminde mezar." },
    { terim: "Kurultay", anlam: "Eski Türklerde ve Moğollarda devlet işlerinin görüşülüp karara bağlandığı meclis." },
    { terim: "Levazım", anlam: "Ordunun ihtiyacı olan malzeme veya bu malzemeyi sağlayan bölüm." },
    { terim: "Lojistik", anlam: "Ordunun türlü gereksinimi ile ilgili işlerin bütünü, geri hizmet." },
    { terim: "Manipüle Etmek", anlam: "Yönlendirmek." },
    { terim: "Medeniyet", anlam: "Bir toplumun maddi ve manevi varlıklarının, fikir ve sanat çalışmalarının tümü; uygarlık." },
    { terim: "Meşruiyet", anlam: "Geçerli olma durumu, meşruluk." },
    { terim: "Metafor", anlam: "Bir kelimeyi kabul edilenin dışında başka anlamlara gelecek biçimde kullanma, mecaz." },
    { terim: "Mevali", anlam: "Azat edilmiş köleler (Emeviler döneminde Arap olmayan Müslümanlar için kullanılmıştır); Osmanlı'da yüksek dereceli ilim adamları." },
    { terim: "Minyatür", anlam: "Işık, gölge ve hacim duygusu yansıtılmayan küçük, renkli resim sanatı." },
    { terim: "Mitolojik", anlam: "Mitolojiyle ilgili, esatirî." },
    { terim: "Monarşi", anlam: "Siyasi otoritenin genellikle miras yolu ile bir kişinin üzerinde toplandığı devlet düzeni." },
    { terim: "Muhteva", anlam: "İçerik." },
    { terim: "Muvazzaf", anlam: "Silahlı Kuvvetlerde görev başında olan askerler; bir görevle yükümlü olan." },
    { terim: "Mükellef", anlam: "Yükümlü; eksiksiz yapılmış." },
    { terim: "Müstahkem", anlam: "Sağlamlaştırılmış, tahkim edilmiş." },
    { terim: "Müteferrik", anlam: "Birbirinden ayrılmış, dağılmış olan." },
    { terim: "Müteşekkil", anlam: "Oluşmuş, meydana gelmiş." },
    { terim: "Nalbant", anlam: "Hayvanların ayağına nal çakan kimse." },
    { terim: "Neden-Sonuç", anlam: "Tarihteki olay ve olgular arasındaki bağlantıları belirlemek için kullanılan kavram." },
    { terim: "Neolitik", anlam: "Taş Devri’nin son çağı (Cilalı Taş Devri) ile ilgili." },
    { terim: "Neşredilmek", anlam: "Yayımlanmak." },
    { terim: "Nizam", anlam: "Düzen, sistem." },
    { terim: "Nümismatik", anlam: "Eski para ve madalyaların tarihini ve tanımını inceleyen bilim." },
    { terim: "Obsidiyen", anlam: "Cam kaya, volkanik cam." },
    { terim: "Olay (Tarihî Olay)", anlam: "Belirli bir zaman diliminde meydana gelen, somut ve tarihî önem taşıyan gelişmeler (Örn: İstanbul'un Fethi)." },
    { terim: "Olgu (Tarihî Olgu)", anlam: "Olayların sonuçlarına dayanan, uzun süreli, soyut ve genel süreçler (Örn: Anadolu'nun Türkleşmesi)." },
    { terim: "Olgusal", anlam: "Olayların dayandığı sebep ve sonuçlarla ilgili olan." },
    { terim: "Orak", anlam: "Ekin, ot vb. biçme aracı." },
    { terim: "Özel Mülkiyet", anlam: "Kişinin sahip olduğu taşınır veya taşınmaz mal." },
    { terim: "Paleoantropolog", anlam: "İnsanın anatomik ve biyolojik değişimlerine odaklanan bilim insanı." },
    { terim: "Paleoantropoloji", anlam: "İnsanoğlunun anatomik ve biyolojik değişimlerini inceleyen bilim dalı." },
    { terim: "Paleografi", anlam: "Geçmişte kullanılan yazı çeşitlerini ve bu yazıların özelliklerini inceleyen bilim." },
    { terim: "Papirüs", anlam: "Eski Mısırlıların bir bitkinin saplarından yaptıkları kâğıt." },
    { terim: "Parşömen", anlam: "Yazı yazmak için özel olarak hazırlanan deri." },
    { terim: "Piramit", anlam: "Mısır firavunlarının anıt mezarı." },
    { terim: "Piroteknoloji", anlam: "Ateşin kontrollü kullanımı ve malzeme üretimindeki uygulamalarını inceleyen bilim dalı." },
    { terim: "Politeist", anlam: "Çok tanrılı din yanlısı." },
    { terim: "Reaya", anlam: "Bir hükümdarın yönetimi altındaki halk; Osmanlı'da vergi veren halk." },
    { terim: "Revizyon", anlam: "Yeniden gözden geçirip düzeltme." },
    { terim: "Rölyef", anlam: "Kabartma." },
    { terim: "Saban", anlam: "Çift süren hayvanların koşulduğu demir uçlu tarım aracı." },
    { terim: "Sarnıç", anlam: "Yağmur sularının biriktirildiği üstü kapalı yapı." },
    { terim: "Sav", anlam: "İleri sürülerek savunulan düşünce, tez." },
    { terim: "Senato", anlam: "Eski Roma’da yöneticiler meclisi." },
    { terim: "Sentezleme", anlam: "Fikirleri birleştirerek bir bütün hâline getirme." },
    { terim: "Skolastik", anlam: "Orta Çağ'da inanç ve bilgiyi kiliseyle birleştirmeye çalışan felsefe." },
    { terim: "Sosyoloji", anlam: "Toplumları ve toplumsal olayların neden ve etkilerini inceleyen bilim." },
    { terim: "Strateji", anlam: "Politik, ekonomik ve askerî güçleri bir arada kullanma bilimi ve sanatı." },
    { terim: "Sulak", anlam: "Suyu bol yer." },
    { terim: "Süreli Yayın", anlam: "Belirli aralıklarla yayımlanan dergi vb.." },
    { terim: "Şuur", anlam: "Bilinç." },
    { terim: "Şûra", anlam: "Danışma kurulu." },
    { terim: "Taarruz", anlam: "Saldırı." },
    { terim: "Tablet", anlam: "Üzerinde çivi yazısı ile metin yazılı kil belge." },
    { terim: "Tahıl", anlam: "Buğday, arpa, mısır vb. ürünlerin genel adı." },
    { terim: "Tahrir", anlam: "Yazma, kaydetme; tahrir defterleri." },
    { terim: "Takas", anlam: "Para kullanmadan mal değişimi." },
    { terim: "Taksimat", anlam: "Bölme, bölüştürme işleri." },
    { terim: "Tamga (Damga)", anlam: "Bir şeyin üzerine basılan nişan, işaret." },
    { terim: "Tanzim Etmek", anlam: "Düzenlemek." },
    { terim: "Tarih", anlam: "Geçmişteki insan faaliyetlerini, neden-sonuç ilişkisi içinde, yer ve zaman göstererek, belgelere dayalı olarak inceleyen bilim dalı." },
    { terim: "Tarihçi", anlam: "Geçmişi, günümüze ulaşan belgeler ve kanıtlarla yorumlayan ve yeniden inşa eden kişi." },
    { terim: "Tarih Öncesi (Prehistorya)", anlam: "Tarihin yazılı kaynaklardan öğrenilemeyen dönemleri." },
    { terim: "Tasarruf Etmek", anlam: "Bir malı istediği gibi kullanmak." },
    { terim: "Tasnif", anlam: "Sınıflama, ayırma." },
    { terim: "Tebaa", anlam: "Uyruk, vatanda." },
    { terim: "Teçhizat", anlam: "Donatı, savaş gereçleri." },
    { terim: "Teferruat", anlam: "Ayrıntı, detay." },
    { terim: "Tekemmül Etmek", anlam: "Olgunlaşmak, mükemmel duruma gelmek." },
    { terim: "Tenkit", anlam: "Eleştiri, bilginin doğruluğunu inceleme." },
    { terim: "Testi", anlam: "Geniş gövdeli, dar boğazlı su kabı." },
    { terim: "Topyekûn", anlam: "Eksiksiz, toplu olarak." },
    { terim: "Toy", anlam: "Türk hükümdarlarının verdiği büyük ziyafet, şölen." },
    { terim: "Töre", anlam: "Bir toplulukta benimsenmiş davranış, kural ve geleneklerin bütünü; yazısız hukuk." },
    { terim: "Turan", anlam: "Türklerin eski yurtları; dünyadaki Türkleri birleştirme ideali." },
    { terim: "Tüccar", anlam: "Ticaret yapan kimse." },
    { terim: "Vahim", anlam: "Ağır ve tehlikeli sonuç doğuracak olan." },
    { terim: "Vakıf", anlam: "Bir hizmetin yapılması için ayrılan mülk veya para." },
    { terim: "Vâris", anlam: "Mirasçı." },
    { terim: "Veraset", anlam: "Mirasta hak sahibi olma, kalıtım." },
    { terim: "Veri", anlam: "Bir araştırmanın temeli olan ana öge, data." },
    { terim: "Vesika", anlam: "Belge." },
    { terim: "Vuzuhsuz", anlam: "Belirsiz, niteliği tam bilinmeyen." },
    { terim: "Yalıtılmış", anlam: "İzole edilmiş." },
    { terim: "Yapay Zekâ", anlam: "Bilgisayarın veya robotun akıllı varlıklarla ilişkili görevleri yerine getirme yeteneği." },
    { terim: "Yazıt", anlam: "Bir şey üzerine kazılan yazı, kitabe." },
    { terim: "Yerleşik Hayat", anlam: "İnsanların tarımsal üretimle birlikte kalıcı konutlarda yaşamaya başlaması." },
    { terim: "Yörük", anlam: "Göçebe Türk oymağı." },
    { terim: "Yurt", anlam: "Vatan; göçebe Türk çadırı." },
    { terim: "Yüzyıl", anlam: "Milat başlangıç alınarak 100 yıllık dönemlere ayrılan zaman dilimi." },
    { terim: "Zahit", anlam: "Dinin yasaklarından sakınan, dünya işlerine önem vermeyen kimse." },
    { terim: "Zimmi", anlam: "İslam devleti idaresindeki gayrimüslim tebaa." }
];