const KAYNAKLAR = [
  { yazar: "Altungök, Ahmet", eser: "Sâsânî Kültür ve Medeniyetinin İslâm Kültür ve Medeniyetine Etkileri", detay: "Tarih İncelemeleri Dergisi XXIX / 2, 2014, 445-487." },
  { yazar: "Toğay, Ali Hüseyin", eser: "Sasani Devleti’nin Kuruluşu: Hürmüzgân Muharebesi Üzerine Bir Değerlendirme", detay: "Journal of Universal History Studies, 7(2), 2024, 267-285." },
  { yazar: "Altungök, Ahmet", eser: "Siyâsi, İdâri, İktisâdi, Sosyal ve Kültürel Açıdan Sâsânî Devleti (MS. 226-652)", detay: "Fırat Üniversitesi Sosyal Bilimler Enstitüsü Doktora Tezi, Elazığ, 2012." },
  { yazar: "Niray, Nasır", eser: "Sâsâni İmparatorluğu’nun Devlet Yapısı Üzerine Bir İnceleme", detay: "Muğla Üniversitesi SBE Dergisi Güz 2001 Sayı 5." },
  { yazar: "Cihan, Cihad", eser: "Türk-Sasani Askerî İttifakları ve Sasani Ordusunda Türkler", detay: "Mustafa Kemal Üniversitesi Sosyal Bilimler Enstitüsü Dergisi, Cilt: 12, Sayı: 32, 2015, s. 89-107." },
  { yazar: "Sivrioğlu, Ulaş Töre", eser: "Sāsānilerde Askeri Teşkilat, Silah Teknolojisi ve Savaş Stratejileri", detay: "Turkish Studies, Volume 8/5, Spring 2013, p. 675-703." },
  { yazar: "Toğay, Ali Hüseyin", eser: "Sasani - Bizans İlişkileri (VI. ve VII. Yüzyıllar)", detay: "Nevşehir Hacı Bektaş Veli Üniversitesi Sosyal Bilimler Enstitüsü Yüksek Lisans Tezi, Nevşehir, 2018." },
  { yazar: "Alıcı, Mehmet", eser: "Kitap Tanıtımı ve Tenkitler: Touraj Daryaee, Sasanian Persia: The Rise and Fall of an Empire", detay: "İstanbul Üniversitesi İlahiyat Fakültesi Dergisi, 2010, 22, 295-317." },
  { yazar: "Altungök, Ahmet", eser: "Sâsânîler Dönemi İran Tarihi Arkeolojik Kaynakları", detay: "History Studies, 12/4, Ağustos 2020, s. 1419-1439." },
    { yazar: "Karatay, Osman", eser: "Türklerin İslam’ı Kabulü", detay: "Ankara 2018." },
  { yazar: "Golden, Peter B.", eser: "Courts and Court Culture in the Proto-urban and Urban Developments among the Pre-Chinggisid Turkic Peoples", detay: "Turko-Mongol Rulers, Cities and City Life, yay. D. Durand-Guedy vd., Leiden-Boston: Brill, 2013, s. 21-73." },
  { yazar: "Gumilëv, Lev N.", eser: "Eski Türkler", detay: "çev. D. A. Batur, 2. basım, İstanbul 2002." },
  { yazar: "İbn’ül-Esir", eser: "İslam Tarihi", detay: "10 cilt, heyet çevirisi, İstanbul 1986." },
  { yazar: "Khazanov, Anatoly M.", eser: "Göçebe ve Dış Dünya", detay: "çev. Ö. Suveren, İstanbul 2015." },
  { yazar: "Kradin, Nikolay N.", eser: "İmperiya Hunnu", detay: "gen. 2. Baskı, Moskva: Logos, 2001." },
  { yazar: "Lindner, Rudi Paul", eser: "Nomadism, Horses and Huns", detay: "Past and Present, 92 (Ağustos 1981), s. 3-19." },
  { yazar: "Liu Mau-Tsai", eser: "Çin Kaynaklarına Göre Doğu Türkleri", detay: "çev. E. Kayaoğlu - D. Banoğlu, İstanbul, 2006." },
  { yazar: "Pritsak, Omeljan", eser: "The Pečenegs: A Case of Social and Economic Transformation", detay: "Archivum Eurasiae Medii Aevi, 1 (1975), s. 211-235." },
  { yazar: "Salman, Hüseyin", eser: "Türgişler", detay: "Ankara 1998." },
  { yazar: "Szádeczky-Kardoss, Samuel", eser: "Avarlar", detay: "çev. R. Sezer, Erken İç Asya Tarihi, 2. baskı, İstanbul 2000, s. 283-310." },
  { yazar: "Şeşen, Ramazan", eser: "İslam Coğrafyacılarına Göre Türkler ve Türk Ülkeleri", detay: "2. baskı, Ankara 1998." },
  { yazar: "Vaissière, Étienne de la", eser: "Early Medieval Central Asian Population Estimates", detay: "Journal of the Economic and Social History of the Orient, LX/6 (2017), s. 788-817." },
  { yazar: "Taşağıl, Ahmet", eser: "Gök-Türkler I", detay: "Türk Tarih Kurumu, 2. Baskı, Ankara 2003." },
  { yazar: "Taşağıl, Ahmet", eser: "Gök-Türkler II (Fetret Devri 630-681)", detay: "Türk Tarih Kurumu, Ankara 1999." },
  { yazar: "Taşağıl, Ahmet", eser: "Gök-Türkler III", detay: "Türk Tarih Kurumu, Ankara 2004." },
  { yazar: "Kurat, Akdes Nimet", eser: "Göktürk Kağanlığı", detay: "Türkler, Cilt: 2, s. 49-78." },
  { yazar: "Togan, İsenbike", eser: "Göktürklerle İlgili Çince Kaynaklarda Söylem: Chiu T'ang-Shu'dan Örneklerle", detay: "Belleten Dergisi." },
  { yazar: "Erkoç, Hayrettin İhsan", eser: "Çin ve Tibet Kaynaklarına Göre Göktürk Mitleri", detay: "Belleten Dergisi, Cilt: 82, Sayı: 293, Nisan 2018, s. 51-82." },
  { yazar: "Grousset, Rene", eser: "Bozkır İmparatorluğu", detay: "İstanbul 1980." },
  { yazar: "Golden, Peter B.", eser: "Türk Halkları Tarihine Giriş: Ortaçağ ve Erken Yeniçağ’da Avrasya ve Ortadoğu’da Etnik Yapı ve Devlet Oluşumu", detay: "çev. Osman Karatay, Ötüken Neşriyat, İstanbul, 2017." },
  { yazar: "Eberhard, Wolfram", eser: "Çin Tarihi", detay: "Ankara 1987." },
  { yazar: "Kafesoğlu, İbrahim", eser: "Türk Millî Kültürü", detay: "Ötüken Neşriyat, İstanbul, 2002." },
  { yazar: "Christian, David", eser: "A History of Russia, Central Asia and Mongolia", detay: "Oxford 1998." },
  { yazar: "Czegledy, Karol", eser: "Turan Kavimlerinin Göçü", detay: "Terc. G. Karaağaç, İstanbul 1999." },
  { yazar: "Donuk, Abdulkadir", eser: "Eski Türk Devletlerinde İdari Askeri unvan ve Terimler", detay: "İstanbul 1988." },
  { yazar: "Eberhard, Wolfram", eser: "Çinin Şimal Komşuları", detay: "Ankara 1942." },
  { yazar: "Merçil, Erdoğan", eser: "İlk Müslüman Türk Devletleri", detay: "Ankara 2000." },
  { yazar: "Hsüe, Tsung-cheng", eser: "T'u-chüe Shih", detay: "Pekin 1992." },
  { yazar: "Ögel, Bahaeddin", eser: "Türk Mitolojisi (I. Cilt)", detay: "Türk Tarih Kurumu Yayınları, Ankara, 2010." },
{ yazar: "Ögel, Bahaeddin", eser: "Uygur Devletinin Teşekkülü ve Yükseliş Devri", detay: "Belleten Dergisi, Cilt 19, Ankara, 1955." },
{ yazar: "Çakan, Varis", eser: "Orhun Uygur Devleti Ordusu'nun Silahlanması ve Eğitimi Üzerine Bir İnceleme", detay: "TSA Dergisi, Yıl: 10, Sayı: 1-2, Nisan - Ağustos 2006." },
{ yazar: "Terzioğlu, Ahmet Haldun", eser: "Göktürkler", detay: "Panama Yayıncılık, Ankara, 2015." },
{ yazar: "Taşağıl, Ahmet", eser: "Uygurlar (-840'tan önce-)", detay: "Bilge Kültür Sanat Yayınları, İstanbul, 2020." },
{ yazar: "Ahmetbeyoğlu, Ali", eser: "Uygurlar", detay: "İstanbul Üniversitesi Açık ve Uzaktan Eğitim Fakültesi Yayınları, 2010." },
{ yazar: "Çandarlıoğlu, Gülçin", eser: "Uygurlar", detay: "TDV İslâm Ansiklopedisi, 42. Cilt, İstanbul, 2012." },
{ yazar: "Yıldırım, Kürşat", eser: "Uygur Kağanlığı'nın Tarihî Coğrafyası", detay: "Türk Dünyası Araştırmaları, Cilt: 120, Sayı: 236, Eylül - Ekim 2018." },
{ yazar: "Çandarlıoğlu, Gülçin", eser: "Uygur Devletleri Tarihi ve Kültürü", detay: "Türkler, Cilt: 2, Sayfa: 193-214." },
{ yazar: "Çandarlıoğlu, Gülçin", eser: "Uygurlar", detay: "TDV İslâm Ansiklopedisi, 42. Cilt, İstanbul, 2012." },
{ yazar: "Bilinmiyor", eser: "Uygur Kağanlığı'nın Kuruluş ve Yükseliş Dönemi", detay: "Akademik İnceleme / Ders Notu." },
{ yazar: "Bilinmiyor", eser: "Uygur Kağanlığı (744-840)", detay: "Akademik İnceleme / Ders Notu." },
{ yazar: "İzgi, Özkan", eser: "Uygurların Siyasi ve Kültürel Tarihi (Hukuk Vesikalarına Göre)", detay: "Türk Kültürünü Araştırma Enstitüsü Yayınları, Ankara, 1987." },
{ yazar: "Ömer, Uçqunjan; Niyaz, İbrahim; Tabıshxan, Toxtı", eser: "Uyğur Xelq Tarixiy Qoşaqliri", detay: "Kaşgar Uygur Neşriyatı, 2008." },
{ yazar: "Gedikli, Yusuf (Der.)", eser: "Hunlar ve Göktürkler Üzerine", detay: "Post Yayın Dağıtım, İstanbul, 2020." },
{ yazar: "Ahmetbeyoğlu, Ali", eser: "Avrupa Hun İmparatorluğu", detay: "Türk Tarih Kurumu Yayınları, Ankara, 2001." },
{ yazar: "Ercilasun, Ahmet B.", eser: "Dîvânü Lügati't-Türk ve Uygurlar", detay: "Turkish Studies, Volume 4/8, Fall 2009." },
{ yazar: "Veli, Hatice", eser: "Eski Uygurlarda Yerleşik Yaşam Kültürü", detay: "Ötüken Neşriyat, İstanbul, 2021." },
{ yazar: "İzgi, Özkan", eser: "Çin Elçisi Wang Yen-Te'nin Uygur Seyahatnamesi", detay: "Ankara, 1989." },
{ yazar: "Mango, Cyril", eser: "Bizans: Yeni Roma İmparatorluğu", detay: "Çeviren: Gül Çağalı Güven, Yapı Kredi Yayınları, 2008." },
{ yazar: "Gregory, Timothy E.", eser: "A History of Byzantium", detay: "Blackwell Publishing, 2005." },
{ yazar: "Pralong, Annie (Ed.)", eser: "Bizans: Yapılar, Meydanlar, Yaşamlar", detay: "Çeviri: Buket Kitapçı-Bayrı, Kitap Yayınevi, 2011." },
{ yazar: "Baştav, Şerif", eser: "Bizans İmparatorluğu Tarihi: Son Devir (1261 - 1461)", detay: "Türk Kültürünü Araştırma Enstitüsü Yayınları, 1989." },
{ yazar: "Ciliv, Serra (Ed.)", eser: "Cogito - Bizans (Sayı: 17)", detay: "Yapı Kredi Yayınları, Kış 1999." },
{ yazar: "Norwich, John Julius", eser: "Bizans I: Erken Dönem (MS 323-802)", detay: "Çeviren: Hamide Koyukan, Kabalcı Yayınevi, 2013." },
{ yazar: "Norwich, John Julius", eser: "Bizans II: Yükseliş Dönemi (MS 803-1081)", detay: "Çeviren: Selen Hırçın Riegel, Kabalcı Yayınevi, 2013." },
{ yazar: "Norwich, John Julius", eser: "Bizans III: Gerileme ve Çöküş Dönemi (MS 1082-1453)", detay: "Çeviren: Selen Hırçın Riegel, Kabalcı Yayınevi, 2013." },
{ yazar: "Daley, Brian E. (Ed.)", eser: "Leontius of Byzantium: Complete Works", detay: "Oxford Early Christian Texts, Oxford University Press, 2016." },
{ yazar: "Cormack, Robin ve Vassilaki, Maria", eser: "Byzantium 330-1453", detay: "Royal Academy of Arts, Londra, 2008." },
];
