const KAYNAKLAR = [
    { yazar: "Sayın, Abdurrahman Vefik", eser: "Tekâlif Kavaidi, Osmanlı Vergi Tarihi", detay: "Maliye Nezareti, 1999 [1908]." },
    { yazar: "Sayar, Ahmet Güner", eser: "Osmanlı'da İlim ve Tefekkür Dünyası", detay: "Ötüken Neşriyat, 2007." },
    { yazar: "Mumcu, Ahmet", eser: "Hukuksal ve Siyasal Düşünce Tarihi Açısından Divan-ı Hümayun", detay: "Birey ve Toplum Yayınları, 1986." },
    { yazar: "Mumcu, Ahmet", eser: "Osmanlı Devleti'nde Rüşvet", detay: "İnkılâp Kitabevi." },
    { yazar: "Ocak, Ahmet Yaşar", eser: "Osmanlı Toplumunda Zındıklar ve Mülhidler", detay: "Tarih Vakfı Yurt Yayınları, 1998." },
    { yazar: "Ocak, Ahmet Yaşar", eser: "Osmanlı'da Heterodoksi ve Senkretizm: Bektaşilik Örneği", detay: "Osmanlı Araştırmaları, 2002." },
    { yazar: "Raymond, André", eser: "Osmanlı Döneminde Arap Kentleri", detay: "Tarih Vakfı Yurt Yayınları, 1995." },
    { yazar: "Wheatcroft, Andrew", eser: "The Enemy at the Gate: Habsburgs, Ottomans and the Battle for Europe", detay: "Basic Books, 2008." },
    { yazar: "Wheatcroft, Andrew", eser: "The Ottomans: Dissolving Images", detay: "Viking, 1993." },
    { yazar: "Pagden, Anthony", eser: "Lords of All the World: Ideologies of Empire", detay: "Yale University Press, 1995." },
    { yazar: "Reid, Anthony", eser: "Southeast Asia in the Age of Commerce", detay: "Yale University Press, 1988." },
    { yazar: "Kuran, Aptullah", eser: "Anadolu Medreseleri", detay: "ODTÜ Yayınları." },
    { yazar: "Kuran, Aptullah", eser: "Mimar Sinan", detay: "Hürriyet Vakfı Yayınları, 1986." },
    { yazar: "Salzmann, Ariel", eser: "Tocqueville in the Ottoman Empire: Rival Paths to the Modern State", detay: "Brill, 2004." },
    { yazar: "Tezcan, Baki", eser: "The Second Ottoman Empire: Political and Social Transformation in the Early Modern World", detay: "Cambridge University Press, 2010." },
    { yazar: "Tezcan, Baki", eser: "The Politics of Early Modern Ottoman Historiography", detay: "Cambridge University Press, 2007." },
    { yazar: "Lewis, Bernard", eser: "İslam'ın Krizi", detay: "Literatür Yayıncılık, 2004." },
    { yazar: "Behar, Cem", eser: "A Neighborhood in Ottoman Istanbul: Fruit Vendors and Civil Servants in the Kasap İlyas Mahalle", detay: "SUNY Press, 2003." },
    { yazar: "Kafadar, Cemal", eser: "Between Two Worlds: The Construction of the Ottoman State", detay: "University of California Press, 1995." },
    { yazar: "Kafadar, Cemal", eser: "The Question of Ottoman Decline", detay: "Harvard Middle Eastern and Islamic Review, 1997-1998." },
    { yazar: "Kafadar, Cemal", eser: "İki Cihan Aresinde: Osmanlı Devletinin Kuruluşu", detay: "Birleşik Yayıncılık, 2010." },
    { yazar: "Imber, Colin", eser: "The Ottoman Empire, 1300-1650: The Structure of Power", detay: "Palgrave Macmillan, 2002." },
    { yazar: "Fleischer, Cornell", eser: "Bureaucrat and Intellectual in the Ottoman Empire: The Historian Mustafa Ali", detay: "Princeton University Press, 1986." },
    { yazar: "Quataert, Donald", eser: "The Ottoman Empire 1700-1922", detay: "Cambridge University Press, 2005." },
    { yazar: "İhsanoğlu, Ekmeleddin", eser: "Osmanlı Coğrafya Literatürü Tarihi", detay: "IRCICA, 2000." },
    { yazar: "İhsanoğlu, Ekmeleddin", eser: "History of the Ottoman State Society and Civilisation", detay: "IRCICA, 2001." },
    { yazar: "İhsanoğlu, Ekmeleddin", eser: "Osmanlı Medreseleri", detay: "İslam Tarih, Sanat ve Kültür Araştırma Merkezi, 1999." },
    { yazar: "Evliya Çelebi", eser: "Seyahatname", detay: "Çeşitli Baskılar (17. yüzyıl)." },
    { yazar: "Fernández-Armesto, Felipe", eser: "Pathfinders: A Global History of Exploration", detay: "W. W. Norton, 2006." },
    { yazar: "Braudel, Fernand", eser: "Akdeniz ve Akdeniz Dünyası", detay: "İmge Kitabevi / Metis Yayınları, 1993." },
    { yazar: "Piterberg, Gabriel", eser: "An Ottoman Tragedy: History and Historiography at Play", detay: "University of California Press, 2003." },
    { yazar: "Ágoston, Gábor", eser: "Guns for the Sultan", detay: "Cambridge University Press, 2005." },
    { yazar: "Hosking, Geoffrey", eser: "Rusya ve Ruslar", detay: "İletişim Yayınları, 2002." },
    { yazar: "Parker, Geoffrey", eser: "Küresel Kriz: Savaş, İklim Değişikliği ve 17. Yüzyılda Kıyamet", detay: "Tarih Vakfı, 2015." },
    { yazar: "Veinstein, Gilles", eser: "Commercial Relations between India and the Ottoman Empire", detay: "Franz Steiner Verlag, 1991." },
    { yazar: "Veinstein, Gilles", eser: "L'Empire ottoman et le commerce asiatique au XVIe siècle", detay: "Revue du Monde Musulman, 1990." },
    { yazar: "Necipoğlu, Gülru", eser: "The Age of Sinan: Architectural Culture in the Ottoman Empire", detay: "Princeton University Press, 2005." },
    { yazar: "Necipoğlu, Gülru", eser: "The Topkapi Scroll: Geometry and Ornament in Islamic Architecture", detay: "Getty Center, 1995." },
    { yazar: "İnalcık, Halil", eser: "Osmanlı İmparatorluğu: Klasik Çağ (1300-1600)", detay: "Yapı Kredi Yayınları, 2003." },
    { yazar: "İnalcık, Halil", eser: "Fatih Devri Üzerinde Tetkikler ve Vesikalar", detay: "Türk Tarih Kurumu, 1954." },
    { yazar: "İnalcık, Halil", eser: "Land Problems in Ottoman History", detay: "The Muslim World, 1955." },
    { yazar: "İnalcık, Halil", eser: "Military and Fiscal Transformation in the Ottoman Empire", detay: "Archivum Ottomanicum, 1980." },
    { yazar: "İnalcık, Halil", eser: "The Ottoman State: Economy and Society", detay: "Cambridge University Press, 1994." },
    { yazar: "İnalcık, Halil", eser: "Osmanlı ve Avrupa", detay: "Sözcü Kitabevi, 2018." },
    { yazar: "İnalcık, Halil", eser: "Şair ve Patron: Patrimonyal Devlet ve Sanat Üzerinde Bir Çalışma", detay: "Doğu Batı Yayınları, 2003." },
    { yazar: "İnalcık, Halil", eser: "Osmanlı İmparatorluğu: Toplum ve Ekonomi", detay: "Eren Yayıncılık, 1993." },
    { yazar: "İnalcık, Halil", eser: "The Heyday and Decline of the Ottoman Empire", detay: "Cambridge University Press, 1970." },
    { yazar: "Sahillioğlu, Halil", eser: "Slaves in the Social and Economic Life of Bursa", detay: "Turcica, 1985." },
    { yazar: "Sahillioğlu, Halil", eser: "Osmanlı Para Tarihinde Dünya Para ve Maden Hareketlerinin Yeri", detay: "ODTÜ Gelişme Dergisi, 1978." },
    { yazar: "Sahillioğlu, Halil", eser: "Osmanlılarda Para Darlığının Siyasi Sonuçları", detay: "Güneydoğu Avrupa Araştırmaları Dergisi, 1973-1974." },
    { yazar: "el-Akhisarî, Hasan Kâfi", eser: "Usûlü'l-Hikem fî Nizâmi'l-Âlem", detay: "Sadeleştirme: M. İpşirli, (1596)." },
    { yazar: "Peçevi, İbrahim", eser: "Peçevi Tarihi", detay: "Kültür Bakanlığı, 1992." },
    { yazar: "Ortaylı, İlber", eser: "Osmanlı İmparatorluğu'nda İktisadi ve Sosyal Değişim", detay: "Turhan Kitabevi, 2000." },
    { yazar: "Ortaylı, İlber", eser: "Osmanlı'yı Yeniden Keşfetmek", detay: "Timaş Yayınları, 2006." },
    { yazar: "Tekeli, İlhan & İlkin, Selim", eser: "Para ve Kredi Sisteminin Oluşumunda Bir Aşama: Osmanlı'da İaşe Sistemi", detay: "ODTÜ Yayınları, 1982." },
    { yazar: "Tekeli, İlhan & İlkin, Selim", eser: "Osmanlı İmparatorluğu'nda Eğitim ve Bilgi Üretim Sisteminin Oluşumu ve Dönüşümü", detay: "Türk Tarih Kurumu, 1993." },
    { yazar: "Wallerstein, Immanuel", eser: "Modern Dünya Sistemi", detay: "Aram Yayıncılık / Yarın Yayınları, 2004-2011." },
    { yazar: "Uzunçarşılı, İsmail Hakkı", eser: "Osmanlı Devleti Teşkilâtından Kapıkulu Ocakları", detay: "Türk Tarih Kurumu, 1943." },
    { yazar: "Uzunçarşılı, İsmail Hakkı", eser: "Osmanlı Tarihi", detay: "Türk Tarih Kurumu Yayınları." },
    { yazar: "Uzunçarşılı, İsmail Hakkı", eser: "Osmanlı Devleti'nin İlmiye Teşkilâtı", detay: "Türk Tarih Kurumu, 1965." },
    { yazar: "Uzunçarşılı, İsmail Hakkı", eser: "Osmanlı Devleti'nin Saray Teşkilatı", detay: "Türk Tarih Kurumu, 1945." },
    { yazar: "Thornton, John K.", eser: "Africa and Africans in the Making of the Atlantic World 1400–1800", detay: "Cambridge University Press, 1998." },
    { yazar: "von Hammer-Purgstall, Joseph", eser: "Osmanlı İmparatorluğu Tarihi", detay: "Üçdal Neşriyat." },
    { yazar: "Raby, Julian", eser: "Vezir and His Painter", detay: "Muqarnas, 1990." },
    { yazar: "Raby, Julian", eser: "Mehmed the Conqueror's Greek Scriptorium", detay: "Dumbarton Oaks Papers, 1983." },
    { yazar: "Barkey, Karen", eser: "Eşkıyalar ve Devlet: Osmanlı Tarzı Devlet Merkezileşmesi", detay: "Tarih Vakfı Yurt Yayınları, 1999." },
    { yazar: "Çelebi, Katip", eser: "Fezleke", detay: "Cerîde-i Havâdis Matbaası, 1870." },
    { yazar: "Çelebi, Katip", eser: "Düstûrü'l-Amel li-Islâhi'l-Halel", detay: "Çeşitli Baskılar (1653)." },
    { yazar: "Çelebi, Katip", eser: "Mîzânü'l-Hakk fî İhtiyâri'l-Ahakk", detay: "Marifet Yayınları, 1981." },
    { yazar: "Çelebi, Katip", eser: "Cihannümâ", detay: "Türkiye Yazma Eserler Kurumu Başkanlığı, 2013." },
    { yazar: "Çelebi, Katip", eser: "Keşfü'z-Zunûn", detay: "Çeşitli Baskılar." },
    { yazar: "Silay, Kemal", eser: "Nedim and the Poetics of the Ottoman Court", detay: "Indiana University Turkish Studies, 1994." },
    { yazar: "Pomeranz, Kenneth", eser: "The Great Divergence", detay: "Princeton University Press, 2000." },
    { yazar: "Koçi Bey", eser: "Koçi Bey Risalesi", detay: "Milli Eğitim Bakanlığı, 1985 [1631]." },
    { yazar: "Peirce, Leslie", eser: "Morality Tales: Law and Gender in the Ottoman Court of Aintab", detay: "University of California Press, 2003." },
    { yazar: "Peirce, Leslie", eser: "The Imperial Harem: Women and Sovereignty in the Ottoman Empire", detay: "Oxford University Press, 1993." },
    { yazar: "Peirce, Leslie", eser: "Osmanlı İmparatorluğu'nda Harem ve Egemenlik", detay: "Tarih Vakfı Yurt Yayınları." },
    { yazar: "Köprülü, Mehmed Fuad", eser: "Osmanlı Devleti'nin Kuruluşu", detay: "Türk Tarih Kurumu Yayınları, 1959." },
    { yazar: "Uyar, Mesut & Erickson, Edward", eser: "A Military History of the OttOttomans", detay: "Praeger, 2009." },
    { yazar: "Cook, Michael", eser: "Osmanlı İmparatorluğu'nun Karşılaştırmalı Mali Yapısı", detay: "Akademik Makale." },
    { yazar: "Ursinus, Michael", eser: "Regionalism and Change in the Ottoman Empire 1760-1850", detay: "Harrassowitz, 1993." },
    { yazar: "Ursinus, Michael", eser: "Osmanlı Tarihinde Reformlar ve Yazılı Belgeler", detay: "Toplum ve Bilim, 1996." },
    { yazar: "Ursinus, Michael", eser: "Osmanische Wirtschaftsgeschichte im Überblick", detay: "Osmanlı Araştırmaları, 1992." },
    { yazar: "Akdağ, Mustafa", eser: "Celali İsyanları (1550–1603)", detay: "Ankara Üniversitesi Yayınları, 1963." },
    { yazar: "Al-Tikriti, Nabil", eser: "Kalam in the Service of the State", detay: "I.B. Tauris, 2005." },
    { yazar: "Mustafa Efendi, Naima", eser: "Tarih-i Naima (Ravzatü'l-Hüseyn fi Hulasati Ahbari'l-Hafikayn)", detay: "Matbaa-i Âmire, 1864." },
    { yazar: "Steensgaard, Niels", eser: "The Asian Trade Revolution of the Seventeenth Century", detay: "University of Chicago Press, 1974." },
    { yazar: "Steensgaard, Niels", eser: "Asya Ticaret Devrimi", detay: "İletişim Yayınları, 2001." },
    { yazar: "Sarı, Nil", eser: "Osmanlı Dönemi Tıp Eğitimi ve Darüşşifalar", detay: "Türk-İslam Bilim ve Teknoloji Tarihi Kongresi Bildirileri, 1981." },
    { yazar: "Itzkowitz, Norman", eser: "Ottoman Empire and Islamic Tradition", detay: "University of Chicago Press, 1972." },
    { yazar: "Özel, Oktay", eser: "The Collapse of Rural Order in Ottoman Anatolia: Amasya 1576–1643", detay: "Brill, 2016." },
    { yazar: "Barkan, Ömer Lütfi", eser: "Tarihi Demografinin Meseleleri", detay: "İstanbul Üniversitesi İktisat Fakültesi Mecmuası, 1962." },
    { yazar: "Brummett, Palmira", eser: "Ottoman Seapower and Levantine Diplomacy in the Age of Discovery", detay: "SUNY Press, 1994." },
    { yazar: "Wittek, Paul", eser: "The Rise of the Ottoman Empire", detay: "Royal Asiatic Society, 1938." },
    { yazar: "Piri Reis", eser: "Kitâb-ı Bahriye", detay: "Çeşitli Baskılar." },
    { yazar: "Murphey, Rhoads", eser: "Ottoman Warfare 1500-1700", detay: "UCL Press, 1999." },
    { yazar: "Murphey, Rhoads", eser: "Osmanlı Harp Sanatı 1500–1800", detay: "Kitap Yayınevi, 2009." },
    { yazar: "Murphey, Rhoads", eser: "Osmanlı'da Ordu ve Savaş 1500-1700", detay: "İstanbul, 2007." },
    { yazar: "Abou El-Haj, Rifa'at", eser: "Formation of the Modern State: The Ottoman Empire", detay: "SUNY Press, 1991." },
    { yazar: "Özbaran, Salih", eser: "Osmanlı İmparatorluğu ve Hindistan Yolu", detay: "Tarih Vakfı Yurt Yayınları, 1994." },
    { yazar: "Özbaran, Salih", eser: "Ottoman Naval Policy in the South", detay: "Longman, 1995." },
    { yazar: "Subrahmanyam, Sanjay", eser: "The Portuguese Empire in Asia 1500–1700", detay: "Longman, 1993." },
    { yazar: "Mustafa Efendi, Selaniki", eser: "Tarih-i Selaniki", detay: "Türk Tarih Kurumu, 1989." },
    { yazar: "Kuru, Selim S.", eser: "The Literature of Rum: The Making of a Literary Tradition (1450–1600)", detay: "Cambridge University Press, 2013." },
    { yazar: "Seyyid Lokman", eser: "Hünernâme", detay: "Saray Kroniği / Minyatür Albümü." },
    { yazar: "Shaw, Stanford J.", eser: "History of the Ottoman Empire and Modern Turkey", detay: "Cambridge University Press, 1976." },
    { yazar: "Shaw, Stanford J.", eser: "Osmanlı İmparatorluğu ve Modern Türkiye", detay: "E Yayınları, 1994." },
    { yazar: "Faroqhi, Suraiya", eser: "Approaching Ottoman History: An Introduction to the Sources", detay: "Cambridge University Press, 1999." },
    { yazar: "Faroqhi, Suraiya", eser: "Subjects of the Sultan: Culture and Daily Life in the Ottoman Empire", detay: "I.B. Tauris, 2000." },
    { yazar: "Faroqhi, Suraiya", eser: "The Ottoman Empire and the World Around It", detay: "I.B. Tauris, 2004." },
    { yazar: "Faroqhi, Suraiya", eser: "Osmanlı Kültürü ve Gündelik Yaşam", detay: "Tarih Vakfı Yurt Yayınları / İmge Kitabevi." },
    { yazar: "Soucek, Svat", eser: "Osmanlı Denizgücü: Piri Reis ve Denizciliği", detay: "Kitap Yayınevi, 2015." },
    { yazar: "Soucek, Svat", eser: "Piri Reis and Turkish Mapmaking After Columbus", detay: "Nour Foundation, 1996." },
    { yazar: "Turan, Şerafettin", eser: "Kanuni'nin Oğlu Şehzade Bayezid Vakası", detay: "Türk Tarih Kurumu, 1961." },
    { yazar: "Pamuk, Şevket", eser: "Osmanlı-Türkiye İktisadi Tarihi 1500-1914", detay: "İletişim / Gerçek Yayınevi, 1988/1999." },
    { yazar: "Pamuk, Şevket", eser: "Osmanlı Ekonomisi ve Dünya Kapitalizmi 1820-1913", detay: "Tarih Vakfı Yurt Yayınları, 1994." },
    { yazar: "Pamuk, Şevket", eser: "Osmanlı İmparatorluğu'nda Paranın Tarihi", detay: "Tarih Vakfı Yurt Yayınları, 2000." },
    { yazar: "Pamuk, Şevket", eser: "In the Absence of Domestic Currency", detay: "Journal of Economic History, 1997." },
    { yazar: "Pamuk, Şevket", eser: "Osmanlı Ekonomisi ve Kurumları", detay: "Türkiye İş Bankası Kültür Yayınları, 2007." },
    { yazar: "Tekin, Şinasi", eser: "Osmanlı Edebi Geleneğinde Divan Şiirinin Konumu", detay: "Türklük Bilgisi Araştırmaları, 1990." },
    { yazar: "Ahmed Efendi, Taşköprülüzâde", eser: "eş-Şakâiku'n-Nu'mâniyye fî Ulemâi'd-Devleti'l-Osmâniyye", detay: "İz Yayıncılık, 2007." },
    { yazar: "Işıksal, Turgut", eser: "Osmanlı İmparatorluğu'nda Baharat Ticareti", detay: "Türk Tarih Kurumu Belleten, 1965." },
    { yazar: "Artan, Tülây", eser: "Arts and Architecture", detay: "Cambridge University Press, 2006." },
    { yazar: "Değirmenci, Tülün", eser: "İktidar Oyunları ve Resimli Kitaplar", detay: "Kitap Yayınevi, 2012." },
    { yazar: "Aksan, Virginia", eser: "Whatever Happened to the Janissaries?", detay: "War in History, 1998." },
    { yazar: "Aksan, Virginia & Goffman, Daniel", eser: "The Early Modern Ottomans: Remapping the Empire", detay: "Cambridge University Press, 2007." }
];